
name: video-frame-extractor
version: '0.1'
summary: Video Frame Extraction Tool
description: |
  A tool for extracting frames from video files
  using Python.

base: core22
grade: stable
confinement: strict

parts:
  video-frame-extractor:
    plugin: python
    source: .
    python-packages:
      - opencv-python 
      - fpdf
      - python-pptx
      - PyQt5
      - GPUtil
    build-packages:
      - python3-pip
      - python3-setuptools
    stage-packages:
      - python3
      - python3-pip
      - libgl1-mesa-glx  # Required for OpenCV

apps:
  video-frame-extractor:
    command: bin/python3 $SNAP/src/app.py
    plugs:
      - home
      - network
      - removable-media
